export enum ActionType {
  ADD_BUCKET = 'ADD_BUCKET',
  ADD_CARD = 'ADD_CARD',
  DELETE_BUCKET = 'DELETE_BUCKET',
  DELETE_CARD = 'DELETE_CARD',
  EDIT_BUCKET = 'EDIT_BUCKET',
  EDIT_CARD = 'EDIT_CARD',
  SET_DRAG = 'SET_DRAG',
  SWAP_BUCKETS = 'SWAP_BUCKETS'
}
